
services:

  - type: web
    name: backend
    plan: free
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: nneimark-db
          property: connectionString
      - key: GIGACHAT_CREDENTIALS
        sync: false
      - key: MAX_BOT_TOKEN
        sync: false
      - key: MAX_BOT_NAME
        sync: false

  - type: web
    name: frontend
    plan: free
    runtime: docker
    dockerfilePath: ./frontend/Dockerfile

databases:
  - name: nneimark-db
    plan: free